### ISSUE TITLE
Write page on command-line scripts

### ISSUE THREAD

**Issue by nabobalis** [OpenAstronomy/packaging-guide#12]
Currently blank:
https://packaging-guide.openastronomy.org/en/latest/scripts.html

Things to cover:
- [ ] How to write a command line function that can parse arguments.
- [ ] Adding entry points in setup.cfg
- [ ] Testing those entry points

**Comment by patelaryan7751** [comment]
i want to work on this can you give a little more information. @nabobalis

**Comment by nabobalis** [comment]
Hi @patelaryan7751, while it is great you want to work on OpenAstronomy and its projects. I would not suggest this is a good starting issue to tackle.

**Comment by Cadair** [comment]
The scripts page is now written even if it's very minimal, so I am going to close.
