### ISSUE TITLE
Add a `.gitignore`?

### ISSUE THREAD

**Issue by Cadair** [OpenAstronomy/packaging-guide#19]
We don't automake a git directory, but it is expected (#1), having a ignore would be very useful?

**Comment by Prit2341** [comment]
It hides the file from git status. Especially with many generated files you really don't want them to show up there all the time. It also prevents you from accidentally adding them e.g. when doing git add some folder.
The purpose of gitignore files is to ensure that specific files not tracked by git remain untracked.

I think the .gitingnore file is helpful on some occasions
