### ISSUE TITLE
Finalize user documentation by filling out "needs writing" placeholders

### ISSUE THREAD

**Issue by pllim** [OpenAstronomy/packaging-guide#23]
Particularly:

* https://github.com/OpenAstronomy/packaging-guide/blob/master/docs/ci.rst
* https://github.com/OpenAstronomy/packaging-guide/blob/master/docs/scripts.rst

Motivation: Astropy cannot reroute people from [package-template](https://github.com/astropy/package-template) to this site if this site appears unfinished.

Blocks:

* astropy/package-template#519

**Comment by Cadair** [comment]
Duplicate of #12 #8 and #7
