### ISSUE TITLE
Is this right?

### ISSUE THREAD

**Issue by bmorris3** [OpenAstronomy/packaging-guide#67]
Seems the tox test uses pytest to look inside `packagename` – is that right?

https://github.com/OpenAstronomy/packaging-guide/blob/470750ba7d43b0ecbe3e8b707d4d154782790362/%7B%7B%20cookiecutter.package_name%20%7D%7D/tox.ini#L55

Should that be a key in the template?

**Comment by Cadair** [comment]
yes, you are correct, that should be `{{ cookiecutter.module_name }}` as well. thanks!
