### ISSUE TITLE
Write page on continuous integration

### ISSUE THREAD

**Issue by namurphy** [OpenAstronomy/packaging-guide#8]
The page on [continuous integration](https://packaging-guide.openastronomy.org/en/latest/ci.html) still needs to be written.  Possible topics include:

 - How to decide which CI platform to choose
 - Using GitHub Actions
 - Setting up Azure Pipelines
 - Travis CI
 - Circle CI
 - How to cache large data files in tests (see also #7)

**Comment by Cadair** [comment]
@namurphy we recently wrote this page, if you wanted to take a look and make any suggestions that would be great.
